// <auto-generated />
using System;
using API_projekat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_projekat.Migrations
{
    [DbContext(typeof(PonudaPodizvodjacaContext))]
    [Migration("20220923133025_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API_projekat.Models.PonudaPodizvodjaca", b =>
                {
                    b.Property<int>("IDponude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDponude"), 1L, 1);

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DatumPredaje")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazivPonude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDponude");

                    b.ToTable("PonudePodizvodjaca");
                });

            modelBuilder.Entity("API_projekat.Models.TezaUSP", b =>
                {
                    b.Property<int>("IDUSP")
                        .HasColumnType("int");

                    b.Property<int>("JMBG")
                        .HasColumnType("int");

                    b.Property<int>("IDponude")
                        .HasColumnType("int");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUSP", "JMBG", "IDponude", "RedniBroj");

                    b.ToTable("teze");
                });

            modelBuilder.Entity("API_projekat.Models.UgovorSaPodizvodjacem", b =>
                {
                    b.Property<int>("IDUSP")
                        .HasColumnType("int");

                    b.Property<int>("JMBG")
                        .HasColumnType("int");

                    b.Property<int>("IDponude")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumZakljucenja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RokIzvrsenja")
                        .HasColumnType("datetime2");

                    b.HasKey("IDUSP", "JMBG", "IDponude");

                    b.HasIndex("IDponude");

                    b.HasIndex("JMBG");

                    b.ToTable("Ugovori");
                });

            modelBuilder.Entity("API_projekat.Models.Zaposleni", b =>
                {
                    b.Property<int>("JMBG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JMBG"), 1L, 1);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozicija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JMBG");

                    b.ToTable("Zaposleni");
                });

            modelBuilder.Entity("API_projekat.Models.TezaUSP", b =>
                {
                    b.HasOne("API_projekat.Models.UgovorSaPodizvodjacem", null)
                        .WithMany("Teze")
                        .HasForeignKey("IDUSP", "JMBG", "IDponude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_projekat.Models.UgovorSaPodizvodjacem", b =>
                {
                    b.HasOne("API_projekat.Models.PonudaPodizvodjaca", "Ponuda")
                        .WithMany()
                        .HasForeignKey("IDponude")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_projekat.Models.Zaposleni", "Zaposleni")
                        .WithMany()
                        .HasForeignKey("JMBG")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("Zaposleni");
                });

            modelBuilder.Entity("API_projekat.Models.UgovorSaPodizvodjacem", b =>
                {
                    b.Navigation("Teze");
                });
#pragma warning restore 612, 618
        }
    }
}
